language: node_js
node_js:
  - node
  - 8
  - 7
  - 6
env:
  - TZ=GMT
  - TZ='Pacific/Kiritimati'
  - TZ='Etc/GMT+12'
matrix:
  exclude:
    - node_js: 8
      env: TZ='Pacific/Kiritimati'
    - node_js: 8
      env: TZ='Etc/GMT+12'
    - node_js: 7
      env: TZ='Pacific/Kiritimati'
    - node_js: 7
      env: TZ='Etc/GMT+12'
    - node_js: 6
      env: TZ='Pacific/Kiritimati'
    - node_js: 6
      env: TZ='Etc/GMT+12'
